### ISSUE TITLE
write install script for custom name

### ISSUE THREAD

**Issue by xeon-zolt** [Bashmug/betty#2]
write install script for custom name so that people can install Betty with different names too like i want to use name zoya or mac
and then use the same instead of betty

**Comment by arr-dev** [comment]
I'd take a stab at this for hacktoberfest

**Comment by gavinwade12** [comment]
You can check out my changes at PR #3

**Comment by xeon-zolt** [comment]
after testing i will close the issue
PR #3 is merged @gavinwade12
